version: "3.8"
services:
  hostel-app-database:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWD}
      - MYSQL_DATABASE=${MYSQL_DB}
    ports:
      - '${MYSQL_PORT}:${MYSQL_PORT}'
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
      - my-db:/var/lib/mysql
 
 hostel-app-server:
    image: payara/server-full
    ports:
      - '${PAYARA_MANAGER_PORT}:${PAYARA_MANAGER_PORT}'
      - '${PAYARA_DEPLOYMENT_PORT}:${PAYARA_DEPLOYMENT_PORT}'
      - '8181:8181'
    restart: always
    volumes:
      - ./deployments:/opt/payara41/deployments
      - ./logs:/opt/payara41/glassfish/domains/payaradomain/logs
      - ./vvvConfiguration:/opt/vdz/config
    working_dir: /opt/payara41/bin/
    environment:
      - PAYARA_DOMAIN=${PAYARA_DOMAIN}
volumes:
  my-db:
